### ISSUE TITLE
Migrate from DockerHub automation to GitHub Actions?

### ISSUE THREAD

**Issue by ansemjo** [ansemjo/speedtest-plotter#11]
Tagging @tuxpeople here because I noticed they have a fork with GitHub Actions CI that builds the container image. I like that.

If you read this, Thomas:
* be aware that there have been a number of changes and fixes in this repository since your fork, you might want to rebase.
* would you like to prepare a pull request with your CI stuff in this repository?

**Comment by tuxpeople** [comment]
Hi Anton

I'd be happy to prepare a PR. Please bear with me, it may take a while as I'm very busy at the moment. Your target will ne Docker Hub, right?

Thanks for letting me know about the changes. I'm a bit lost pulling changes from upstream back into my forks. Not so much a git guru, I'm afraid. Once the PR is prepared and merged, I may close my fork anyways. As far as I remember, I just did it because I needed a arm64 Image :-D

Br
Thomas

**Comment by ansemjo** [comment]
> I'd be happy to prepare a PR. Please bear with me, it may take a while as I'm very busy at the moment.

Sure! There's no pressure at all! :)

> Your target will ne Docker Hub, right?

Yes. If it helps, I also started pushing to GitHub packages at https://github.com/users/ansemjo/packages/container/package/speedtest, which is currently a feature preview. I'm sure there is some nice integration with GitHub Actions aswell.

> [...] As far as I remember, I just did it because I needed a arm64 Image :-D

I see, the DockerHub image does not run because it is built on `x86_64`, eh?

**Comment by tuxpeople** [comment]
> > [...] As far as I remember, I just did it because I needed a arm64 Image :-D
> 
> I see, the DockerHub image does not run because it is built on `x86_64`, eh?

Yes. And I never figured out how to do multi-arch builds with dockerhub builds.

**Comment by tuxpeople** [comment]
I'd trow away my fork and made a new one, to start again from your current code. Had some issues, but looks like I'm on a good way. Looking forward to make the pull request soon. Hopefully.

**Comment by ansemjo** [comment]
Thank you!

Yeah, I saw that you had some trouble with the correct Dockerfile context .. sorry for moving that away :innocent:

I'm learning a few new tools as well .. despite all the Dockerfiles I've written, I've never used hadolint so far :grimacing:

**Comment by tuxpeople** [comment]
hadolint is cool, as it "enforces" you to use best practices for your dockerfile and also ```shellcheck``` the scripts used in your dockerfile.

**Comment by tuxpeople** [comment]
It should run trough in about 15mins: https://github.com/tuxpeople/docker-speedtest-plotter/runs/2369178116
