### ISSUE TITLE
Use of TESTSERVER

### ISSUE THREAD

**Issue by tuxpeople** [ansemjo/speedtest-plotter#16]
I tried to use the `TESTSERVER` environment variable. It's not documented I think, but used as I can see from the python code. In the "old" version, which made use of speedtest-cli (?) I successfully used `SERVERID`. But `TESTSERVER` does not work correctly. I tried it with two different servers. If I set `TESTSERVER`, I see the correct `Server ID` in the log. But `Ping`, `Download` and `Upload` are all 0:

```
{'Server ID': '12743', 'Sponsor': '', 'Server Name': '', 'Timestamp': '2021-04-17T16:00:00+00:00', 'Distance': '', 'Ping': '0', 'Download': '0.000000', 'Upload': '0.000000', 'Share': '', 'IP Address': 'xxxxxxxxxxxxxxxx'} 
```

If I do not specify a specific server, it works:

```
{'Server ID': 'sonic.wingo.ch:8080', 'Sponsor': 'Wingo', 'Server Name': 'Herden', 'Timestamp': '2021-04-17T16:15:01+00:00', 'Distance': '19.1232', 'Ping': '1', 'Download': '573563353.904221', 'Upload': '610659238.040191', 'Share': '', 'IP Address': 'xxxxxxxxxxxxxxx'}
```

I'd like to choose the server I want to use, because I think it's important to use your own provider's server, if they have one. Otherwise you are testing your providers network, the interconnection to another provider and that other providers network as well.

Any idea what's going wrong here? Is it the other client you are using internally now? Or is it just me, being stupid?

**Comment by ansemjo** [comment]
Ah damn, and there I was hoping nobody was using that feature anyway. Sorry. :grimacing:

Yes, it's not documented, I should change that. And I changed the name of the variable on purpose because unfortunately they have different meanings. `speedtest-cli` expects an ID, as you have given it. But SpeedTest++ expects a `host:port` combination. Therefore, if you set `TESTSERVER` to `sonic.wingo.ch:8080` it should work.

**Comment by ansemjo** [comment]
The reason I haven't documented it yet, I believe, is because I found no elegant way to find a suitable `host:port`. But I just found that you can go to https://c.speedtest.net/speedtest-servers-static.php and receive a list of 100 servers "close" to you, so you can pick one.

**Comment by ansemjo** [comment]
The documentation has been added with 9d1284d. Please report back if setting `TESTSERVER` like this fixes it for you. :)

**Comment by tuxpeople** [comment]
So it was basically me being stupid :-) It should have known that a option which has changed it's name couldn't be used the same way as before. Thanks for you link. It looks like it is sorted reverse, as the servers closest to me are at the bottom. And `speedtest-cli --list` knows servers which aren't on that list. But the list works for me. Thanks!

And yes, `-e TESTSERVER='sonic.wingo.ch:8080'`works like expected.

And the link in the documentation is even better, at least it looks like it's beeing sorted better and it has the server I was missing in the other list :-)

**Comment by ansemjo** [comment]
I wouldn't say that. Missing documentation for a breaking change is on me. ;)

Yeah, I edited my comment above because the JSON API seems to return better results – and allows searching.
