### ISSUE TITLE
`MINUTES`: max 60?

### ISSUE THREAD

**Issue by fritzmg** [ansemjo/speedtest-plotter#169]
Just a minor issue: setting `MINUTES` to anything above `60` is currently ignored - i.e. it will still run the test every 60 minutes instead of e.g. every 120 minutes, if you set it to `120`.

Just wanted to confirm whether this is a known issue or known limitation currently - as you can still used `SCHEDULE="*/2 * * * *"` alternatively for example.

**Comment by ansemjo** [comment]
Yeah, this isn't explicitly documented but is expected when you look at the line in `entrypoint.sh`, which adds the cron job:
https://github.com/ansemjo/speedtest-plotter/blob/fdfa53fc735165ff92304732f52b9e9aff378fb5/container/entrypoint.sh#L17

What you probably want is [`SCHEDULE="* */2 * * *"`](https://crontab.guru/#*_*/2_*_*_*) as your example would run every two minutes instead.

**Comment by fritzmg** [comment]
> Yeah, this isn't explicitly documented but is expected when you look at the line in entrypoint.sh, which adds the cron job:

Ok, thank you for the clarification :). Just wanted to mention it in case anyone else stumbles over this.

> What you probably want is [`SCHEDULE="0 */2 * * *"`](https://crontab.guru/#0_*/2_*_*_*) as your example would run every two minutes instead.

Yes, that's what I meant 😁
