### ISSUE TITLE
Old data disappeared

### ISSUE THREAD

**Issue by tuxpeople** [ansemjo/speedtest-plotter#18]
Did the database format change since you moved from speedtest-cli to speedtest++? I'm asking because I updated my main deployment now, and I cant see any data. Also, the csv is empty. But the database has some size:

```
[root@forseti pvc-119498c9-2b38-478e-9d0c-7af88562c44d_speedtest-plotter_speedtest-plotter-data]# ls -l
total 248
-rw-r--r-- 1 root root 217088 Apr 17 19:16 speedtests.db
-rw-r--r-- 1 root root  32768 Apr 17 19:16 speedtests.db-shm
-rw-r--r-- 1 root root      0 Apr 17 19:16 speedtests.db-wal
```

**Comment by ansemjo** [comment]
I hope not. I took care to map the new JSON format from SpeedTest++ to the old column names.

Depending on how old your previous measurements are, they might simply not be in view anymore. :smile:
I changed the way the query works in 6e2cbfb0ef4ae1cfe11fb1139716ed07a980b9e8. It now returns the last `7d` as in actual seven days and not just the *previous n results*. Just enter a large number like 2000 without any `d` or `h` suffix in the first form field and it should show you your old results.

**Comment by tuxpeople** [comment]
It now made the first measurement with the new set up:

```
-rw-r--r-- 1 root root 217088 Apr 17 19:16 speedtests.db
-rw-r--r-- 1 root root  32768 Apr 17 19:33 speedtests.db-shm
-rw-r--r-- 1 root root   4152 Apr 17 19:30 speedtests.db-wal
```

It has changed the other files, but not the "db" file. Is this expected? I can see the new measurement in the the UI. I'll try to rollback to the old image.

**Comment by tuxpeople** [comment]
Ok, rolling back to the old image and the data is back.

And I see the new measurement in the old image:
![Bildschirmfoto 2021-04-17 um 19 40 02](https://user-images.githubusercontent.com/1506076/115121822-05cab600-9fb5-11eb-8d13-b45df228359f.png)

Looking at the csv, I see the measurements stopped working 10 days ago:
```
28472,Wingo,Herden,2021-04-07T20:45:01.013277Z,19.123352576481953,6.882,134182783.4493135,300197610.92809516,,144.2.103.28
28472,Wingo,Herden,2021-04-07T21:15:01.012461Z,19.123352576481953,8.075,186483640.09486094,348852598.35775316,,144.2.103.28
28472,Wingo,Herden,2021-04-07T21:45:01.022146Z,19.123352576481953,8.141,191441762.37552908,312675744.9452098,,144.2.103.28
28472,Wingo,Herden,2021-04-07T22:15:01.024112Z,19.123352576481953,8.356,165964290.85627782,311586544.53039414,,144.2.103.28
speedtest.wingo.ch:8080,,,2021-04-17T17:30:01+00:00,,1,853638251.550521,802910711.406954,,144.2.103.28
```

I can't replace the `7d` with `14d`:
![Bildschirmfoto 2021-04-17 um 19 46 19](https://user-images.githubusercontent.com/1506076/115121945-a4571700-9fb5-11eb-9c72-f6ec3cac388e.png)

The CSV report then just says `Invalid isoformat string: '2021-04-07T22:15:01.024112Z'`

**Comment by ansemjo** [comment]
Ugh. Sorry. I'm cooking right now, therefore I am a little slow to reply. :P
If you're willing to send me your database files I can take a look and try to find a fix later ..

> It has changed the other files, but not the "db" file. Is this expected? I can see the new measurement in the the UI. I'll try to rollback to the old image.

Yes, the sqlite driver started using a write-ahead log (`-wal`). As long as you keep those three files together it should continue to hold all your data. I'll look into a way to turn that off, I believe there was a flag I could pass.

**Comment by tuxpeople** [comment]
I don't expect realtime support :-) I don't expect support at all, as it's a free project and I do not have a paid support contract :-)

Take your time. Here are the files: https://www.dropbox.com/s/ou48zij3r407ees/speedtest-db.tar.gz?dl=1

**Comment by ansemjo** [comment]
Thanks. Those were both relatively quick fixes, fortunately.

Commit 11778b0ca0021dbc22cf17cd2b464a692641c03a turns off `sqlite_wal_mode`. I can see that the driver still creates those files as long as the process is running but it shouldn't *actually use* the `-wal` for new writes anmore. On clean shutdowns it will also delete both additional files again.

And in eec79ed867f1f92a6b7234da767b0fa41531434c I've added a `try: .. except ..: ..` fallback to parse old timestamps from the database with `dateutil.parser` when the simpler `datetime.fromisoformat` fails. Testing with the database you provided I can now see both old and new values. :)

**Comment by tuxpeople** [comment]
thank's, I'll test it and will provide feedback.

The pipeline was mine (since I got it from somewhere else [I forgot where] and changed it the way I needed it), now its completely yours ;-)

**Comment by tuxpeople** [comment]
Working great now, thanks!

![Bildschirmfoto 2021-04-17 um 20 41 32](https://user-images.githubusercontent.com/1506076/115123444-61993d00-9fbd-11eb-9f53-2fd5f7674039.png)
