### ISSUE TITLE
seems like import doesn't work

### ISSUE THREAD

**Issue by Snawe** [ansemjo/speedtest-plotter#47]
Hey,

I run the docker container like this `docker run -d -p 8000:8000 -e MARKER_DOWNLOAD=40 -e MARKER_UPLOAD=10 --privileged --volume /home/pi/data:/data ansemjo/speedtest`

And I wanted to import some data that I exported previously (haven't used the --volume before), but the database stays empty.

I did:
`docker exec 812827bd398f dump > results.csv`
and wanted to import it into the new one with
`docker exec 1f3fcca1a2fb import < results.csv`
but the database in ~/data stays empty as well as the graph.

Any ideas?

**Comment by ansemjo** [comment]
My first idea is – if that is the *exact* command that you used to import – that you're missing the `-i` flag to attach stdin to the exec process? I.e. try `docker exec -i .... import < results.csv`?

**Comment by Snawe** [comment]
Yes, that solved the issue! Thanks.

**Comment by ansemjo** [comment]
Great! Closing this issue then. :)
