### ISSUE TITLE
[Feat] Any way to define the default time? (18H vs 7D, for ex)

### ISSUE THREAD

**Issue by jaxjexjox** [ansemjo/speedtest-plotter#53]
Subject covers it really, thanks for the hard work.

**Comment by ansemjo** [comment]
Yes, you can set it in your bookmark via a URL query parameter for example, see #44.

**Comment by ansemjo** [comment]
@jaxjexjox does that cover your requirement? Or would you prefer an ENV for that aswell?

**Comment by jaxjexjox** [comment]
Honestly I'd prefer to set a cookie, do an ENV but hey, look it's free and you've done a good job, so it's no biggie - thank you for the hard work.

**Comment by ansemjo** [comment]
Hey @jaxjexjox, I just wanted to let you know that the new release v0.5.1 will have this feature. The default time limit can be set with `FETCH_LIMIT`, e.g. `... -e FETCH_LIMIT=18h ...`.
