### ISSUE TITLE
Improvement proposal: Allow for different y-axes for down- and upstream

### ISSUE THREAD

**Issue by moeffju** [ansemjo/speedtest-plotter#6]
As most consumer ISP offerings are asymmetric, it would be great if the plot would offer an additional y axis so that downstream and upstream could both be plotted at “full height”.

Optionally, in combination with #5 the scale could be changed to % of expected bandwidth instead of absolute bandwidth.

(Of course the most amazing thing would be to have a client-side graph rendering that allows this configuration on the fly and also lets one hover over specific data points.)

**Comment by ansemjo** [comment]
These are great ideas, thank you! My roommate mentioned the upstream having a different scaling than the downstream as well .. but I fear that this is currently not possible with the way I am rendering the graph in GNUplot – the second axis is used by the ping measurements already.

Going forward, this should probably be implemented – like you say – in client-side graph rendering. But then at which point would you just write a data exporter and reuse an existing time-series database and graphing tool, e.g. Grafana? It isn't too hard to import the CSV output from speedtest-cli and I have had a docker-compose setup as an experiment to demonstrate that. But that would make the entire setup much more complex if you don't have Grafana or something similar running already.

**Comment by moeffju** [comment]
Yeah, the big benefit of speedtest-plotter IMO is that it’s self-contained. I had a super hacky version to log speeds but never got around to make it actually pretty or reliable. If I had had to set up extra grafana or anything I would never have done it.

**Comment by moeffju** [comment]
I think there’s a way to use have multiple y-axes with gnuplot, cf. https://stackoverflow.com/questions/27390317/how-to-plot-multiple-y-axes, but I haven’t tried it (yet).

**Comment by ansemjo** [comment]
You're right, there is a possibility to use `set multiplot` and adjust the `yrange` in between the commands .. I'm on it but it still looks a little messy:

![dump](https://user-images.githubusercontent.com/11139925/79232517-e65ff100-7e67-11ea-9620-bfce3535f338.png)

**Comment by ansemjo** [comment]
This is the current `plotscript` for later reference but I am scrapping this exploration for now ... this seems too complicated with gnuplot while keeping it useful.

```
# Copyright (c) 2019 Anton Semjonov
# Licensed under the MIT License

# set input and output format, enable multiplot mode
set xdata time
set timefmt "%Y-%m-%dT%H:%M:%S.*Z"
set datafile separator ","
set terminal svg size 1280, 720 dynamic
set output ARG2
set multiplot

# set margins to add labels later
set bmargin screen 0.1
set tmargin screen 0.9
set lmargin screen 0.2
set rmargin screen 0.9

# calculate averages per dimension
set fit quiet logfile "/dev/null"
avgping(x) = ping
fit avgping(x) ARG1 using 4:6 via ping
avgdown(x) = down
fit avgdown(x) ARG1 using 4:7 via down
avgup(x) = up
fit avgup(x) ARG1 using 4:8 via up

# ----- plot pings -----
set yrange [0:1]
set xtics format "" out
set ytics format "" out
set y2label "Ping"
set y2tics format "%.0f ms" nomirror out
set y2range [0:*]
set linetype 1 lw 1 lc rgb "light-green" pt 9
plot \
  ARG1 using 4:6 title gprintf("Ping (≈ %.0f ms)", avgping(x)) axes x1y2 with points
unset y2label
unset y2tics

# ----- plot upload -----
set grid
set linetype 1 lw 1 lc rgb "#00ff0000"
set linetype 2 lw 3 lc rgb "orange-red"
set ylabel "Upload" textcolor rgb "orange-red" offset -8, 0
set ytics format "%.2s %cBit/s" nomirror textcolor rgb "orange-red" offset -8, 0
set yrange [0:*]
plot \
  ARG1 using 4:8 notitle with steps, \
  ARG1 using 4:8 title gprintf("Upload (≈ %.2s %cBit/s)", avgup(x)) sm bezier

# ----- enable extras -----
# these elements need only be printed once
set grid
set title "Speedtest Results\ngithub.com/ansemjo/speedtest-plotter"
set timestamp
set xlabel "Measurement Date (UTC)"
set xtics format "%Y-%m-%d\n%H:%M:%S" out font ",10" rotate by -30

# ----- plot download -----
set linetype 1 lw 1 lc rgb "skyblue"
set linetype 2 lw 3 lc rgb "navy"
set ylabel gprintf("Download (≈ %.2s %cBit/s)", avgdown(x)) textcolor rgb "navy" offset 0, 0
set ytics format "%.2s %cBit/s" nomirror textcolor rgb "navy" offset 0, 0
set yrange [0:*]
plot \
  ARG1 using 4:7 notitle with steps, \
  ARG1 using 4:7 title gprintf("Download (≈ %.2s %cBit/s)", avgdown(x)) sm bezier
```

**Comment by ansemjo** [comment]
So, after fixing #5 I revisited this issue again, too. With a few tweaks the above multiplot approach actually looks decent.
There's now .. four main modes how you can combine the new marker and scale flags:

1) No `MARKER_DOWNLOAD`, `MARKER_UPLOAD` or `UPLOAD_SCALE`. The previous default. The plot should look almost identical to before this change.

2) `UPLOAD_SCALE` > 1 is set. For example on asymmetric connections you can "push" the upload bandwidth plot up a little. The y-ticks are split and scales are labelled in two colors.

3) Both markers are set. The y-range is scaled so that both markers lie on the same height. For markers at 250 and 50 this would be equivalent to an upload scale of 5.

4) Both markers are set and the scale is < 1. Like in 2. you can "push" the upload plot down a little. For highly variable measurements the plots might be unreadable otherwise.
