### ISSUE TITLE
Feature Request: Plot Pings with Bars or Line

### ISSUE THREAD

**Issue by Doc-Steve** [ansemjo/speedtest-plotter#62]
Hello, the speedtest-plotter is great. I'm only missing one little thing: ping times are really important when it comes to VOIP etc. and because of Covid provider network usage I have temporary spikes around the day. Unfortunately this important information is not good visualized: you have to search for ping crosses, e.g. sometimes they "hide" near the upload/download lines. 
Proposed solution: plot pings with upright bars or also with a line in different color to clearly see spikes.
Thanks for considering!
Best regards,
Steven

**Comment by ansemjo** [comment]
Hi Steven,

thanks for the suggestion. Indeed, the crosses have bad visibilty when compared to the steps/lines. I've changed that in 6bf873a. Please allow some time for the [build workflow](https://github.com/ansemjo/speedtest-plotter/runs/4581074303?check_suite_focus=true) to run and then repull `latest`.

However, there might be another problem, depending on the range in which your pings usually are. I've added some lines to the `plotscript` a while ago, which bounds the upper axis range. Before that any extreme outlier would rescale the axis until you could no longer discern the normal values.

https://github.com/ansemjo/speedtest-plotter/blob/6bf873a21bce48051f54b93adb02a2b2066550ed/plotscript#L69-L71

If you are instead interested in these maximum values, you'll need to edit the plotscript in a running container:

```diff
diff --git a/plotscript b/plotscript
index 771223d..6d7438c 100644
--- a/plotscript
+++ b/plotscript
@@ -66,16 +66,12 @@ set ylabel "Bandwidth" offset -13, 0
 set xtics format "%Y-%m-%d\n%H:%M:%S" out
 set key right top
 
-# set upper ping range
-pingrange = PING_mean + (3 * PING_stddev)
-if (pingrange < 50) pingrange = 50;
-
 # --> plot ping
 unset ytics
 unset yrange
 set y2label "Ping"
 set y2tics format "%.0f ms" nomirror out
-set y2range [0:pingrange]
+set y2range [0:*]
 set linetype 1 lw 1 lc rgb rgb_ping pt 1
 plot \
   keyentry title " ", \
```

Hope that helps.

**Comment by Doc-Steve** [comment]
Thanks fro the quick reply. That's great. You are right it's not so important to know the detailed ping time of each spike. The important thing to know is how often it exceeds a threshold and spikes. If you want the details you can always download the csv. No need to rescale the whole plot for the spikes of the pings.

**Comment by Doc-Steve** [comment]
Thanks for the suggestion to change the plotfile directly. I added an additional "set style fill solid" to your changed ping plot and now have a very good visual for my special needs.
