### ISSUE TITLE
PermissionError: [Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by Wolf6660** [ansemjo/speedtest-plotter#67]
Hi, 

i ran this app on my Synology in Docker to measure the VPN. Now I want to do the same on my RPI.
Here I get this error:

created directory: '/data'
Traceback (most recent call last):
  File "/opt/speedtest-plotter/./speedtest-plotter", line 6, in <module>
    import subprocess, csv, json, tempfile, sys, argparse, os, io, signal, re, datetime, logging
  File "/usr/local/lib/python3.10/logging/__init__.py", line 57, in <module>
    _startTime = time.time()
PermissionError: [Errno 1] Operation not permitted

can you tell me what i'm doing wrong?

Thanks

**Comment by ansemjo** [comment]
The traceback tells me the error happens on this line in `/usr/local/lib/python3.10/logging/__init__.py`:
```python
_startTime = time.time()
```

So you're not "doing anything wrong" and it's not `speedtest-plotter`'s fault either. A quick search led me to this issue: https://github.com/docker-library/python/issues/674 Thus, maybe try updating your Docker on the Raspberry Pi to the latest version? :)

**Comment by Wolf6660** [comment]
I checked the Version:
Reading package lists... Done
Building dependency tree        
Reading state information... Done
docker-ce is already the newest version (5:19.03.15~3-0~raspbian-stretch).
containerd.io is already the newest version (1.4.3-1).
containerd.io set to manually installed.
docker-ce-cli is already the newest version (5:19.03.15~3-0~raspbian-stretch).
docker-ce-cli set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by ansemjo** [comment]
Hm. Can you try the suggestions from these two links?
* https://wiki.alpinelinux.org/w/index.php?title=Release_Notes_for_Alpine_3.13.0&oldid=19609#time64_requirements
* https://github.com/moby/moby/issues/40734#issuecomment-923032325

**Comment by Wolf6660** [comment]
OK, I updated my RPI to bullseye. Now it works

thank you
