### ISSUE TITLE
Environment Variable "MINUTES" is being ignored?

### ISSUE THREAD

**Issue by aemsx** [ansemjo/speedtest-plotter#72]
I am running the Speedtest-Plotter with "MINUTES=15" but is is being ignored. Tests are run every 30min no matter if I remove the variable completely or set it to anything else. Is there a rate-limit?

**Comment by aemsx** [comment]
Seems to have something to do with #12 - got the same problem (in bridge mode). Speedtest seems to be not running every 15min but 30min (for some reason) if the server list cannot be downloaded. everything runs fine every 15min if a fixed TESTSERVER is set.

**Comment by ansemjo** [comment]
Huh. I'll open this issue back up for now as I want to look into it at some point. Thanks for reporting it!
Personally I haven't used `MINUTES` in quite a while; I defined a custom `SCHEDULE`, which only runs every two hours. But that seems to run as scheduled.

**Comment by aemsx** [comment]
Sample from the raw data:

Server   ID | Sponsor | Server Name | Timestamp
ham.wsqm.telekom-dienste.de.prod.hosts.ooklaserver.net:8080 |   |   | 2022-02-23T20:15:01+01:00
ham.wsqm.telekom-dienste.de.prod.hosts.ooklaserver.net:8080 |   |   | 2022-02-23T20:00:01+01:00
ham.wsqm.telekom-dienste.de.prod.hosts.ooklaserver.net:8080 |   |   | 2022-02-23T19:45:01+01:00
ham.wsqm.telekom-dienste.de.prod.hosts.ooklaserver.net:8080 |   |   | 2022-02-23T19:30:01+01:00
ham.wsqm.telekom-dienste.de.prod.hosts.ooklaserver.net:8080 |   |   | 2022-02-23T19:15:01+01:00
speedtest.xirra.net:8080 | GoHost Server | Nuremberg | 2022-02-23T18:45:01+01:00
speedtest.esrv.center:8080 | Davasto | Falkenstein | 2022-02-23T18:15:01+01:00
speedtest.xirra.net:8080 | GoHost Server | Nuremberg | 2022-02-23T17:45:01+01:00
speedtest-srv03.techniknews.net:8080 | TechnikNews.NET | Falkenstein | 2022-02-23T17:15:01+01:00
speedtest-srv03.techniknews.net:8080 | TechnikNews.NET | Falkenstein | 2022-02-23T16:45:01+01:00

As you can see tests were run every 30min before - no matter if MINUTES was set or not. after adding TESTSERVER to the environment the test ran every 15min as supposed. witout having set the TESTSERVER i ran into the same "Unable to download server list. Try again later" erros that were mentioned in #12 already.

running this in a bridged docker on a QNAP NAS.

**Comment by ansemjo** [comment]
Well .. it looks like our clocks are just too precise. 😬 

I whipped up a simple test script, that attempts to fetch the server list from `https://www.speedtest.net/speedtest-servers.php` continiously and logs an error when this fails:
```bash
#!/usr/bin/env bash

while true; do
  ts=$(date +%s%N)
  curl -Lsv --fail \
    https://www.speedtest.net/speedtest-servers.php \
    >/dev/null 2>"speedtest-servers-$ts"
  if [[ $? -eq 0 ]]; then
    echo -ne "\033[2K\rok: speedtest-servers-$ts"
  else
    echo -e "\033[2K\rerror on: speedtest-servers-$ts"
  fi
  sleep 1
done
```

I started it a couple minutes before 22:00 and this was the result:

```
tmp-trusting-merkle $ bash test.sh 
error on: speedtest-servers-1646082000169513024
error on: speedtest-servers-1646082001508803599
error on: speedtest-servers-1646082003062543524
error on: speedtest-servers-1646082004557869830
error on: speedtest-servers-1646082006391398771
error on: speedtest-servers-1646082007790258111
error on: speedtest-servers-1646082009224040776
error on: speedtest-servers-1646082010617998827
error on: speedtest-servers-1646082012114549702
error on: speedtest-servers-1646082013849634707
ok: speedtest-servers-1646082020790980150^C
```

```
# [...] example from speedtest-servers-1646082000169513024
< HTTP/2 429 
< retry-after: 0
< content-type: text/html
< accept-ranges: bytes
< date: Mon, 28 Feb 2022 21:00:00 GMT
< content-length: 190
* The requested URL returned error: 429
* stopped the pause stream!
* Connection #1 to host c.speedtest.net left intact
```

It appears that the list of servers is updated every full and half hour .. and for a couple seconds around that time, the endpoint simply returns an error.

We should probably catch this error and just retry ~30 seconds later.

**Comment by ansemjo** [comment]
I've added a pretty simple recursive retry with at most three attempts. In my local test this fixed the issue and a measurement was taken at `2022-02-28T21:30:16+00:00` successfully. :)
