### ISSUE TITLE
Possibility for reverse proxy adoption  / Change base url 

### ISSUE THREAD

**Issue by mr-honest** [ansemjo/speedtest-plotter#76]
Hi. 

Would it be too much work for you to allow for reverse proxy, so I can use subfolder directive on nginx?

So instead of **http://domain.com:8000**, I can access by **http://domain.com/speedtest**

I did try different rewrite rules in nginx, and the closest i got was this: 

```
location /speedtest {
        rewrite ^/speedtest(.*)$ $1 break;
        proxy_pass http://speedtest:8000;
    }
```

However this will not load the svg graphics.

**Comment by ansemjo** [comment]
I *think* that all you need to change is add a trailing slash to your `proxy_pass` directive:

```nginx
location /speedtest {
  rewrite ^/speedtest(.*)$ $1 break;
  proxy_pass http://speedtest:8000/;
}
```

I'm not sure though, that's off the top of my head. There is definitely a trick to do this in nginx without needing to change `speedtest-plotter` in any way.

**Comment by mr-honest** [comment]
Hi, I did also try your method, and still the vector graphic would not load. 
I have tried for many hours, and finally it seemed the solution was to change the backend, to allow for url rebase.

**Comment by ansemjo** [comment]
Indeed, that's because the form action and the SVG in the page were using a leading slash. Removing that / changing it to `.` enabled a reverse proxy with a subdirectory location. See diff in b881e48383419c0b80beece7b0acd91dc30da11d.

I tested this locally with an nginx configuration that did not even need a `rewrite` directive:

```nginx
location /speedtest/ { # trailing slash here seems to be important, too
  proxy_pass http://speedtest:8000/;
}
```
