### ISSUE TITLE
Docker env possibility to change how often test is run

### ISSUE THREAD

**Issue by mr-honest** [ansemjo/speedtest-plotter#77]
Hi,

Would it be possible to change how often the script is run, via docker env variable?
Instead of 15 min, for example 2 hours.

**Comment by ansemjo** [comment]
I see you've closed this issue yourself already. Just to document the expected method, for a schedule like "every two hours" you could use: `-e SCHEDULE="20 */2 * * *"`. If you want to use odd hours, you'll need to specify them fully: `-e SCHEDULE="20 1,3,5,7,9,11,13,15,17,19,21,23 * * *"`.
